services:
  db:
    image: postgres:17-alpine
    container_name: blog-db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

#  # Spring Boot Backends
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: false
    ports:
      - "8080:8080"
    networks:
      - blog-network
    restart: on-failure

#  # Spring Boot Backends
  frontend:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
    container_name: blog-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge